# Generated by Django 4.0.1 on 2022-03-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceso', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wisher', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('date_granted', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='acceso.user')),
                ('users_who_liked', models.ManyToManyField(related_name='liked_wishes', to='acceso.User')),
            ],
        ),
    ]
