# Generated by Django 4.0.1 on 2022-03-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theWishingApp', '0002_alter_wish_date_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='date_granted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
