# Generated by Django 4.0.1 on 2022-03-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theWishingApp', '0003_alter_wish_date_granted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='whiser',
            new_name='wisher',
        ),
    ]
