# Generated by Django 4.0.1 on 2022-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theWishingApp', '0004_rename_whiser_wish_wisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='date_granted',
            field=models.DateField(),
        ),
    ]
